service: api
frameworkVersion: "3"

package:
  individually: true

provide: 
  name: aws
  runtime: nodejs18.x
  architecture: arm64
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-south-1'}
  memorySize: 128
  logRetentionInDays: 1
  httpApi:
    cors: true

functions:
  Create_auth_challenge_Lambda_trigger:
    handler: src/handlers/create-auth-challenge-lambda
    iamRoleStatements:
      - Effect: Allow
        Action: lambda:InvokeFunction
        Resource: arn:aws:lambda:ap-south-1:927657138391:function:create-auth-challenge-lambda
        Condition:
          ArnLike:
            AWS:SourceArn: arn:aws:cognito-idp:ap-south-1:927657138391:userpool/ap-south-1_47veqZQCj
      - Effect: Allow
        Action: lambda:InvokeFunction
        Resource: arn:aws:lambda:ap-south-1:927657138391:function:create-auth-challenge-lambda
        Condition:
          ArnLike:
            AWS:SourceArn: arn:aws:cognito-idp:ap-south-1:927657138391:userpool/ap-south-1_c9EbFARCY
      - Effect: Allow
        Action: lambda:InvokeFunction
        Resource: arn:aws:lambda:ap-south-1:927657138391:function:create-auth-challenge-lambda
        Condition:
          ArnLike:
            AWS:SourceArn: arn:aws:cognito-idp:ap-south-1:927657138391:userpool/ap-south-1_AbG5LKYSn

  Define_auth_challenge_Lambda_trigger:
    handler: src/handlers/define-auth-challenge-lambda
    iamRoleStatements:
      - Effect: Allow
        Action: lambda:InvokeFunction
        Resource: arn:aws:lambda:ap-south-1:927657138391:function:define-auth-challenge-lambda
        Condition:
          ArnLike:
            AWS:SourceArn: arn:aws:cognito-idp:ap-south-1:927657138391:userpool/ap-south-1_47veqZQCj
      - Effect: Allow
        Action: lambda:InvokeFunction
        Resource: arn:aws:lambda:ap-south-1:927657138391:function:define-auth-challenge-lambda
        Condition:
          ArnLike:
            AWS:SourceArn: arn:aws:cognito-idp:ap-south-1:927657138391:userpool/ap-south-1_c9EbFARCY
      - Effect: Allow
        Action: lambda:InvokeFunction
        Resource: arn:aws:lambda:ap-south-1:927657138391:function:define-auth-challenge-lambda
        Condition:
          ArnLike:
            AWS:SourceArn: arn:aws:cognito-idp:ap-south-1:927657138391:userpool/ap-south-1_AbG5LKYSn

  Post_confirmation_Lambda_trigger:
    handler: src/handlers/post-confirmation-lambda
    iamRoleStatements:
      - Effect: Allow
        Action: lambda:InvokeFunction
        Resource: arn:aws:lambda:ap-south-1:927657138391:function:post-confirmation-lambda
        Condition:
          ArnLike:
            AWS:SourceArn: arn:aws:cognito-idp:ap-south-1:927657138391:userpool/ap-south-1_AbG5LKYSn

  Verify_auth_challenge_response_Lambda_trigger:
    handler: src/handlers/verify-auth-challenge-lambda
    iamRoleStatements:
      - Effect: Allow
        Action: lambda:InvokeFunction
        Resource: arn:aws:lambda:ap-south-1:927657138391:function:verify-auth-challenge-lambda
        Condition:
          ArnLike:
            AWS:SourceArn: arn:aws:cognito-idp:ap-south-1:927657138391:userpool/ap-south-1_47veqZQCj
      - Effect: Allow
        Action: lambda:InvokeFunction
        Resource: arn:aws:lambda:ap-south-1:927657138391:function:verify-auth-challenge-lambda
        Condition:
          ArnLike:
            AWS:SourceArn: arn:aws:cognito-idp:ap-south-1:927657138391:userpool/ap-south-1_c9EbFARCY
      - Effect: Allow
        Action: lambda:InvokeFunction
        Resource: arn:aws:lambda:ap-south-1:927657138391:function:verify-auth-challenge-lambda
        Condition:
          ArnLike:
            AWS:SourceArn: arn:aws:cognito-idp:ap-south-1:927657138391:userpool/ap-south-1_AbG5LKYSn    